### ISSUE TITLE
feat: support transactions

### ISSUE THREAD

**Issue by LegitPanda** [denodrivers/deno_mongo#362] opened 2022-07-19 17:38 UTC
Hi, great work on this driver so far. It would be nice if it supported transactions - I think I can give this a go if that's ok

**Comment by erfanium** [comment] 2022-07-19 17:51
duplicate of #122

**Closed by erfanium** 2022-07-19 17:51 UTC

**Comment by LegitPanda** [comment] 2022-07-20 16:02
my bad, I searched "transaction" and nothing came up so I assumed it wasn't mentioned already 😅
